---
- name: Install core standard packages
  apt: pkg={{ item }}
  with_items:
    - synaptic
    - nautilus-open-terminal
    - nautilus-wipe
    - wipe
    - gedit-plugins
    - htop
    - meld
    - ubuntu-restricted-extras
    - unity-tweak-tool
    - skype
    - clipit
    - alacarte
    - p7zip-full
    - dconf-tools
    - lftp
    - autojump
    - gksu
    - cifs-utils
    - trash-cli
    - gnome-nettool
    - vlc
    - retext
